mysql:
  host: localhost
  port: 3306
  user: root
  password: 123456
  dbname: realty

server:
  port: 8080

jwt:
  secret: "2c39affd-8238-470b-88e6-39a146c15fc6"
  expire_time: 24

fabric:
  channelName: mychannel
  chaincodeName: mychaincode
  organizations:
    org1:
      mspID: Org1MSP
      certPath: ../../network/crypto-config/peerOrganizations/org1.togettoyou.com/users/User1@org1.togettoyou.com/msp/signcerts
      keyPath: ../../network/crypto-config/peerOrganizations/org1.togettoyou.com/users/User1@org1.togettoyou.com/msp/keystore
      tlsCertPath: ../../network/crypto-config/peerOrganizations/org1.togettoyou.com/peers/peer0.org1.togettoyou.com/tls/ca.crt
      peerEndpoint: localhost:7051
      gatewayPeer: peer0.org1.togettoyou.com
    org2:
      mspID: Org2MSP
      certPath: ../../network/crypto-config/peerOrganizations/org2.togettoyou.com/users/User1@org2.togettoyou.com/msp/signcerts
      keyPath: ../../network/crypto-config/peerOrganizations/org2.togettoyou.com/users/User1@org2.togettoyou.com/msp/keystore
      tlsCertPath: ../../network/crypto-config/peerOrganizations/org2.togettoyou.com/peers/peer0.org2.togettoyou.com/tls/ca.crt
      peerEndpoint: localhost:27051
      gatewayPeer: peer0.org2.togettoyou.com
