mysql:
  host: localhost
  port: 3306
  user: root
  password: 123456
  dbname: realty

server:
  port: 8080

jwt:
  secret: "your-256-bit-secret"  # 在生产环境中使用更强的密钥
  expire_time: 24  # token 过期时间（小时）

fabric:
  channelName: mychannel
  chaincodeName: mychaincode
  org1MSPID: Org1MSP
  cryptoPath: ../../network/crypto-config/peerOrganizations/org1.togettoyou.com
  certPath: ../../network/crypto-config/peerOrganizations/org1.togettoyou.com/users/User1@org1.togettoyou.com/msp/signcerts
  keyPath: ../../network/crypto-config/peerOrganizations/org1.togettoyou.com/users/User1@org1.togettoyou.com/msp/keystore
  tlsCertPath: ../../network/crypto-config/peerOrganizations/org1.togettoyou.com/peers/peer0.org1.togettoyou.com/tls/ca.crt
  peerEndpoint: localhost:7051
  gatewayPeer: peer0.org1.togettoyou.com
